server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    # add custom headers
    add_header X-Custom-Header "Hello from Nginx!";
    add_header X-Server-Time $date_local;

    # setting cache
    location ~* \.(css|js|jpg|png)$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
    }

    # 404 error page
    error_page 404 /404.html;

    # redirect
    location /old-page {
        return 301 /index.html;
    }

    # JSON Response
    location /api/hello {
        default_type application/json;
        return 200 '{"message": "Hello, World!", "status": "ok"}';
    }

    location /api/error {
        return 500 '{"error": "Internal Server Error"}';
    }

    location /api/created {
        default_type application/json;
        return 201 '{"message": "Resource created successfully", "status": "created"}';
    }

    location /api/no-content {
        return 204;
    }

    location /api/rate-limit {
        default_type application/json;
        return 429 '{"message": "Rate Limited", "status": "rate limited"}';
    }

    location /api/data {
        default_type application/json;

        if ($request_method !~ ^(GET|POST)$ ) {
            return 405;
        }

        return 200;
    }
}