server {
    listen 80;
    server_name localhost;
    # redirect to https
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;" always;

    root /usr/share/nginx/html;
    index index.html;
}